- name: Create folder [mysqld log]
  file: path={{ log_dir }}/mysqld
         state=directory
         owner=mysql
         group=vagrant
         mode=775
  tags: install

- name: Touch [mysqld/error.log]
  file: path={{ log_dir }}/mysqld/error.log
         state=touch
         owner=mysql
         group=mysql
         mode=644
  tags: install

- name: Touch [mysqld/slow_query.log]
  file: path={{ log_dir }}/mysqld/slow_query.log
         state=touch
         owner=mysql
         group=mysql
         mode=644
  tags: install

- name: Touch [mysqld/query.log]
  file: path={{ log_dir }}/mysqld/query.log
         state=touch
         owner=mysql
         group=mysql
         mode=644
  tags: install

- name: Transfer [logrotate.d/mysql]
  copy: src={{ templates_path }}/etc_logrotate.d/mysql
            dest=/etc/logrotate.d/mysql
            owner=root
            group=root
            mode=0644
  tags: install

- name: Transfer [my.cnf]
  copy: src={{ templates_path }}/my.cnf
            dest=/etc/my.cnf
            owner=mysql
            group=mysql
            mode=0664
  notify: Restart mysqld
  tags: settings
  