
- name: Transfer [git-completion]
  synchronize: src={{ files_path }}/git-completion/
               dest={{ tools_path }}/git-completion
  tags: settings

- name: Transfer [~/.bach_profile]
  copy: src={{ templates_path }}/bash_profile
        dest=/home/{{ owner }}/.bash_profile
        owner={{ owner }}
        group={{ group }}
        mode=644
  become: no
  tags: settings


- name: Transfer [~/.bashrc]
  copy: src={{ templates_path }}/bashrc
        dest=/home/{{ owner }}/.bashrc
        owner={{ owner }}
        group={{ group }}
        mode=644
  become: no
  tags: settings


- name: Transfer [~/.my.cnf]
  copy: src={{ templates_path }}/my.cnf
        dest=/home/{{ owner }}/.my.cnf
        owner={{ owner }}
        group={{ group }}
        mode=644
  become: no
  tags: settings

- name: Transfer [~/.vimrc]
  copy: src={{ templates_path }}/vimrc
        dest=/home/{{ owner }}/.vimrc
        owner={{ owner }}
        group={{ group }}
        mode=644
  become: no
  tags: settings

