- name: Transfer [~/.bach_profile]
  copy: src=templates/bash_profile
        dest=/home/{{ owner }}/.bach_profile
        owner={{ owner }}
        group={{ group }}
        mode=644
  tags: settings

- name: Transfer [~/.bashrc]
  copy: src=templates/bashrc
        dest=/home/{{ owner }}/.bashrc
        owner={{ owner }}
        group={{ group }}
        mode=644
  tags: settings

- name: Transfer [~/.my.cnf]
  copy: src=templates/my.cnf
        dest=/home/{{ owner }}/..my.cnf
        owner={{ owner }}
        group={{ group }}
        mode=644
  tags: settings

- name: Transfer [~/.vimrc]
  copy: src=templates/vimrc
        dest=/home/{{ owner }}/.vimrc
        owner={{ owner }}
        group={{ group }}
        mode=644
  tags: settings

