# Install

- name: Install [ wget ]
  yum: name=wget state=present
  tags: install

- name: Install [ unzip ]
  yum: name=unzip state=present
  tags: install

- name: Install [ ansible ]
  yum: name=ansible state=present
  tags: install

- name: Install [ libselinux-python ]
  yum: name=libselinux-python state=present
  tags: install



# Settings

- name: Transfer [ /etc/security/limits.conf ]
  copy: src=templates/security_limits.conf
           dest=/etc/security/limits.conf
  tags: settings

- name: Transfer [ /etc/sysconfig/clock ]
  copy: src=templates/sysconfig_clock
           dest=/etc/sysconfig/clock
  tags: settings

- name: Transfer [ /etc/sysconfig/i18n ]
  copy: src=templates/sysconfig_i18n
           dest=/etc/sysconfig/i18n
  tags: settings

