# CMS Drupal7

- name: Existence of Drupal7 directory
  stat: path={{ httpd_document_root }}/drupal7
  register: drupal7
  tags: admin

- name: Create a new database with name 'drupal7'
  become_user: vagrant
  mysql_db:
    name: drupal7
    state: present
  when: not drupal7.stat.exists
  tags: admin

- name: Download Drupal7
  get_url: url="https://ftp.drupal.org/files/projects/drupal-7.54.tar.gz" dest={{ httpd_document_root }}/
  when: not drupal7.stat.exists
  tags: admin

- name: Unarchive drupal-7.54.tar.gz
  unarchive: src={{ httpd_document_root }}/drupal-7.54.tar.gz dest={{ httpd_document_root }}/ copy=no
  when: not drupal7.stat.exists
  tags: admin

- name: Create a symbolic link of Drupal7
  file: src={{ httpd_document_root }}/drupal-7.54 dest={{ httpd_document_root }}/drupal7 state=link
  when: not drupal7.stat.exists
  tags: admin

- name: Remove drupal-7.54.tar.gz
  file: path={{ httpd_document_root }}/drupal-7.54.tar.gz state=absent
  when: not drupal7.stat.exists
  tags: admin

#  cd $PATH_WWW/$DIR_HTML/$DIR
#  mkdir sites/default/files
#  sudo chmod g+w sites/default/files
#  cp sites/default/default.settings.php sites/default/settings.php
#  sudo chown -R vagrant:vagrant $PATH_WWW/$DIR_HTML/$DIR
#
#  cd profiles/standard/translations
#  wget -q http://ftp.drupal.org/files/translations/7.x/drupal/$DRUPAL.ja.po

