- name: Create admin folder
  file: path={{ httpd_document_root }}/admin
         state=directory
         owner={{ owner }}
         group={{ group }}
         mode=775
  tags: admin

- name: Existence of Bootstrap directory
  stat: path={{ httpd_document_root }}/admin/bootstrap
  register: bootstrap
  tags: admin

- name: Download bootstarp
  get_url: url="http://getbootstrap.com/2.3.2/assets/bootstrap.zip" dest={{ httpd_document_root }}/admin
  when: not bootstrap.stat.exists
  tags: admin

- name: Unarchive bootstrap.zip
  unarchive: src={{ httpd_document_root }}/admin/bootstrap.zip dest={{ httpd_document_root }}/admin/ remote_src=True
  when: not bootstrap.stat.exists
  tags: admin

- name: Remove bootstrap.zip
  file: path={{ httpd_document_root }}/admin/bootstrap.zip state=absent
  when: not bootstrap.stat.exists
  tags: admin

# admin/index.php

- name: Transfer admin page
  copy: src={{ templates_path }}/admin/index.php
        dest={{ httpd_document_root }}/admin/index.php
  tags: admin
 
#phpinfo

- name: Transfer phpinfo
  copy: src={{ templates_path }}/admin/phpinfo.php
        dest={{ httpd_document_root }}/admin/phpinfo.php
  tags: admin

# admin/memcache.php
- name: Transfer memcache.php
  copy: src={{ templates_path }}/admin/memcache.php
        dest={{ httpd_document_root }}/admin/memcache.php
  tags: admin

# admin/mail_test.php
- name: Transfer mail_test.php
  copy: src={{ templates_path }}/admin/mail_test.php
        dest={{ httpd_document_root }}/admin/mail_test.php
  tags: admin
 
# admin/mail-test.php
- name: Transfer mail-test.php
  copy: src={{ templates_path }}/admin/mail-test.php
        dest={{ httpd_document_root }}/admin/mail-test.php
  tags: admin

# Opcache
- name: Git clone opcache
  git: repo=https://github.com/rlerdorf/opcache-status.git
       dest={{ templates_path }}/admin/opcache-status
 

