- name: Install Java8
  yum: name=java-1.8.0-openjdk-devel.x86_64
  tags: install

- name: add group "Elasticsearch"
  group: name={{ elastic_group }}
  tags: install

- name: add user "Elasticsearch"
  user: name={{ elastic_user }} group={{ elastic_group }} home=/home/{{ elastic_user }} createhome=no
  tags: install

  # Settings
  
- name: Transfer [elasticsearch.yml]
  copy: src={{ templates_path }}/etc/elasticsearch.yml 
           dest={{ elastic_conf_dir }}/elasticsearch.yml
  notify: Restart elasticsearch
  tags: settings

- name: Transfer [jvm.options]
  copy: src={{ templates_path }}/etc/jvm.options
           dest={{ elastic_conf_dir }}/jvm.options
  notify: Restart elasticsearch
  tags: settings

- name: Transfer [log4j2.properties]
  copy: src={{ templates_path }}/etc/log4j2.properties
           dest={{ elastic_conf_dir }}/log4j2.properties
  notify: Restart elasticsearch
  tags: settings

- name: Transfer [sysconfig/elasticsearch]
  copy: src={{ templates_path }}/sysconfig/elasticsearch
           dest=/etc/sysconfig/elasticsearch
  notify: Restart elasticsearch
  tags: settings

