    - name: Transfer /etc/elasticsearch/elasticsearch.yml
      copy: src=templates/etc/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml owner=vagrant group=vagrant mode=0664
      notify: Restart elasticsearch
      tags: elasticsearch

    - name: Transfer /etc/elasticsearch/jvm.options
      copy: src=templates/etc/jvm.options dest=/etc/elasticsearch/jvm.options owner=vagrant group=vagrant mode=0664
      notify: Restart elasticsearch
      tags: elasticsearch

    - name: Transfer /etc/elasticsearch/log4j2.properties
      copy: src=templates/etc/log4j2.properties dest=/etc/elasticsearch/log4j2.properties owner=vagrant group=vagrant mode=0664
      notify: Restart elasticsearch
      tags: elasticsearch

    - name: Transfer sysconfig/elasticsearch
      copy: src=templates/sysconfig/elasticsearch dest=/etc/sysconfig/elasticsearch owner=vagrant group=vagrant mode=0664
      notify: Restart elasticsearch
      tags: elasticsearch

