    - name: create php log folder
      command: mkdir /var/log/php
      args: 
        creates: /var/log/php
      tags: php

    - name: touch php/php-error.log
      command: touch /var/log/php/php_errors.log
      args: 
        creates: /var/log/php/php_errors.log
      tags: php

    - name: /var/log/php change modify
      file:
        path: /var/log/php
        owner: vagrant
        group: vagrant
        mode: u=rwX,g=rX,o=rX
        recurse: yes
      tags: php

    - name: transfer /etc/logrotate.d/php
      copy: src=../templates/logrotate.d/php dest=/etc/logrotate.d/php owner=root group=root mode=0664
      tags: php

    - name: transfer php.ini
      copy: src=../templates/php/php.ini dest=/etc/php.ini owner=vagrant group=vagrant mode=0664
      notify: Restart httpd
      tags: php

    - name: transfer httpd/conf.d/php.conf
      copy: src=../templates/php/httpd_conf.d/php.conf dest=/etc/httpd/conf.d/php.conf owner=vagrant group=vagrant mode=0664
      notify: Restart httpd
      tags: php

